services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs:/htdocs:ro
    # networks:
    #   - laravel-app_laravel
    depends_on:
      - app

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./htdocs:/htdocs
    # networks:
    #   - laravel-app_laravel

# networks:
#   laravel-app_laravel:
#     external: true  # Reference the existing network
