services:
  web:
    image: nginx:latest
    ports:
      - "8002:80"
      - "4000:443"
    volumes:
      - ./nginx/conf.d/public.conf:/etc/nginx/conf.d/default.conf
      - ./htdocs:/htdocs:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - crazywolf-lausanne

  app:
    build:
      dockerfile: ./php/Dockerfile
    volumes:
      - ./htdocs:/htdocs
    networks:
      - crazywolf-lausanne

networks:
  crazywolf-lausanne:
    driver: bridge
